POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "Inception",
    "release_year": 2010,
    "run_time": 148,
    "rating": 8.8,
    "meta_score": 74,
    "votes": "Inception",
    "gross": 292.58,
    "directorId": 1, 
    "genres": [1, 2], 
    "actors": [1, 2, 3] 
}
